### ISSUE TITLE
qrels.train.addition.tsv not found

### ISSUE THREAD

**Issue by 1024er** [microsoft/SimXNS#1]
Traceback (most recent call last):
  File "co_training/co_training_marco_generate.py", line 401, in <module>
    main()
  File "co_training/co_training_marco_generate.py", line 392, in main
    get_new_dataset(args, model, global_step, renew_tools)
  File "co_training/co_training_marco_generate.py", line 354, in get_new_dataset
    renew_tools.get_question_topk(train_q, train_q_embed, train_q_embed2id, ground_truth_path,
  File "/SimXNS/SimANS/co_training/co_training_generate.py", line 439, in get_question_topk
    train_pos_qp, train_pos_qp_add = load_pos_examples(mode)
  File "/SimXNS/SimANS/co_training/co_training_generate.py", line 141, in load_pos_examples
    with open(file_add) as inp:
FileNotFoundError: [Errno 2] No such file or directory: 'data/MS-Pas/qrels.train.addition.tsv'

@lx865712528

**Comment by lx865712528** [comment]
Please check out [this section](https://github.com/microsoft/SimXNS/tree/main/SimANS#-how-to-use) and download the dataset. Thanks!

**Comment by lx865712528** [comment]
Thanks for pointing it out! If you are working on MS-Pas, you will need this [additional file](https://msranlcir.blob.core.windows.net/simxns/SimANS/data/MS-Pas/qrels.train.addition.tsv) for training.

**Comment by kailashhambarde** [comment]
Hi did you able to download check points?

**Comment by lx865712528** [comment]
The original question seems resolved. For the file downloading issue, please refer to #5. Thanks!
